stages:
  - build
  - test
  - deploy
  
cache:
  paths:
    - Tagx00.Backend/.gradle/wrapper/
    - Tagx00.Backend/.gradle/caches/
    - Tagx00.Frontend/node_modules/

# backendBuildJob:
#   stage: build
#   script:
#     - cd ./Imagex00.Backend/
#     - chmod +x gradlew
#     - ./gradlew assemble

frontendBuildJob:
  image: node:taobao
  stage: build
  script:
    - cd ./Tagx00.Frontend
    - npm install
    - npm run build


# backendTestjob:
#   stage: test
#   script:
#     - cd ./Imagex00.Backend/
#     - chmod +x gradlew
#     - ./gradlew test
#   only:
#     - develop
#     - master

frontendTestJob:
  image: node:taobao
  stage: test
  script:
    - cd ./Tagx00.Frontend/
    - npm install
    - npm run test
  only:
    - develop
    - master

backendDeployJob:
  image: gradle:4.6.0-jdk8-alpine
  stage: deploy
  script:
    - cd ./Tagx00.Backend/
    - chmod +x ./deploy/deploy.sh
    - chmod +x gradlew
    - ./gradlew shadowJar
    - ./deploy.sh
  only:
    - master

frontendDeployJob:
  image: node:taobao
  stage: deploy
  script:
    - cd ./Tagx00.Frontend/
    - chmod +x ./deploy/deploy.sh
    - npm install
    - npm run build
    - ./deploy/deploy.sh
  only:
    - master


